# Generated by Django 3.1.3 on 2020-12-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='owner',
            field=models.BooleanField(default=False, verbose_name='チーム所有者'),
        ),
    ]
