version: '3.8'

services:
    api:
        build: ./
        command: gunicorn --bind 0.0.0.0:8000 --reload config.wsgi:application
        volumes:
            - ./:/usr/src/
            - static_root:/usr/src/static_root
        ports:
            - 8000:8000
        depends_on:
            - db
        restart: always
    
    https-portal:
        image: steveltn/https-portal:1
        ports:
            - 80:80
            - 443:443
        links:
            - api
        restart: always
        environment:
            STAGE: local
            DOMAINS: 'localhost -> http://api:8000'
        volumes:
            - static_root:/var/www/vhosts/localhost/static:ro
            - ssl_certs:/var/lib/https-portal
            - ./nginx.ssl.conf.erb:/var/lib/nginx-conf/localhost.ssl.conf.erb:ro
    
    db:
        image: postgres:13-alpine
        restart: always
        environment:
            POSTGRES_DB: roomone
            POSTGRES_USER: roomone
            POSTGRES_PASSWORD: passwd
            TZ: Asia/Tokyo
            LANG: ja_JP.utf8
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    ssl_certs:
    static_root:
    pgdata: