# Generated by Django 3.1.3 on 2020-12-27 23:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_member_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='入室時間')),
                ('leaving_time', models.DateTimeField(null=True, verbose_name='退室時間')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams.member')),
            ],
        ),
    ]
